In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
os.chdir('./data/')

In [8]:
img1 = cv2.imread('cat_375.jpg', 1)
img2 = cv2.imread('_.jpeg', 1)

<h3>separate rgb from img<h3>


In [3]:
B, G, R = cv2.split(img2)

print(B)
cv2.imshow('B', G)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[244 244 245 ...  39  39  40]
 [244 243 246 ...  39  39  40]
 [244 242 245 ...  40  40  41]
 ...
 [  3   3   3 ...   4   4   4]
 [  2   2   2 ...   5   5   5]
 [  2   2   2 ...   5   5   5]]


QSocketNotifier: Can only be used with threads started with QThread


<h3>concatenate RGB<h3>


In [4]:
img2 = cv2.merge([B, G, R])

cv2.imshow('RGB', img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

<h3>copy head to new place<h3>


In [9]:
head = img2[22:198, 219:356]
img2[0:0+head.shape[0],0:0+head.shape[1]] = head


cv2.imshow('img2', img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

<h3>merge 2 images<h3>


In [10]:
img1 = cv2.imread('cat_375.jpg', 1)
img2 = cv2.imread('_.jpeg', 1)

In [11]:
print(img1.shape)
img2.shape

(720, 1080, 3)


(690, 552, 3)

In [12]:
img1 = cv2.resize(img1, (512, 512))
img2 = cv2.resize(img2, (512, 512))
dst = cv2.add(img1, img2)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
# handle weight

# img1, weight1, img2, weight2, gamma "brightness"
dst = cv2.addWeighted(img1, 0.7, img2, 0.3, 0)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

<h1>Bitwise Operations<h1>
<h4>working with binary images<h4>

In [19]:
img1 = np.zeros((512, 512, 3), np.uint8)
img1 = cv2.rectangle(img1,(200,0), (300,100), (255,255,255),-1)

img2 = np.full((512, 512, 3), 255, np.uint8)  # white image
img2 = cv2.rectangle(img2, (0, 0), (250, 512), (0, 0, 0), -1)

cv2.imshow("img1", img1)
cv2.imshow("img2", img2)


# Bitwise AND
bitwise_and = cv2.bitwise_and(img2, img1)
cv2.imshow("bitwise_and", bitwise_and)

# Bitwise OR
bitwise_or = cv2.bitwise_or(img2, img1)
cv2.imshow("bitwise_or", bitwise_or)

# Bitwise XOR
bitwise_xor = cv2.bitwise_xor(img2, img1)
cv2.imshow("bitwise_xor", bitwise_xor)

# Bitwise NOT
img2_bitwise_not = cv2.bitwise_not(img2)
cv2.imshow("bitwise_not", img2_bitwise_not)
img1_bitwise_not = cv2.bitwise_not(img1)
cv2.imshow("bitwise_not", img1_bitwise_not)

cv2.waitKey(0)
cv2.destroyAllWindows()

<h1>control BGR<h1>


In [28]:
def nothing(x):
    print(x)

img = np.zeros((300,512,3),np.uint8)
cv2.namedWindow('image')

cv2.createTrackbar('B','image',0,255,nothing)
cv2.createTrackbar('G','image',0,255,nothing)
cv2.createTrackbar('R','image',0,255,nothing)

switch = "0 : OFF \n1 : ON"
cv2.createTrackbar(switch,'image',0,1,nothing)

while True:
    cv2.imshow('image',img)
    # wait 1 millisecond and check if any key is pressed if yes break if no continue
    k = cv2.waitKey(1)
    if k == 27:
        break

    b = cv2.getTrackbarPos('B','image')
    g = cv2.getTrackbarPos('G','image')
    r = cv2.getTrackbarPos('R','image')
    s = cv2.getTrackbarPos(switch,'image')

    if s==0:
        img[:,:] = 0
    else:
        img[:,:] = [b,g,r]

cv2.destroyAllWindows()

1
9
19
30
40
51
61
69
77
83
92
102
110
118
125
133
139
146
151
156
158
159
161
164
166
168
171
173
175
178
182
186
190
194
198
200
201
202
