In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import os
os.chdir('./data/')

In [3]:
# show grayScale img
img = cv2.imread('cat_375.jpg',0)
print(img)

[[ 56  56  56 ...  76  76  76]
 [ 56  56  56 ...  76  76  76]
 [ 56  56  56 ...  77  77  77]
 ...
 [150 151 151 ... 113 113 112]
 [147 151 153 ... 113 112 112]
 [145 150 153 ... 112 112 112]]


In [4]:
cv2.imshow('cat',img)
k = cv2.waitKey(0)

if k == 27:  # if i click on esc button "27 == esc"
    cv2.destroyAllWindows()
elif k == ord('s'):
    cv2.imwrite('cat_copy.png',img)
    cv2.destroyAllWindows()

QSocketNotifier: Can only be used with threads started with QThread


In [5]:
# i can choose how many seconds i want the image appear then close it
cv2.imshow('image', img)
cv2.waitKey(5000)          # this mean open the img 5 seconds
cv2.destroyAllWindows()    # then close it

In [6]:
# show colored img
img = cv2.imread('cat_375.jpg', 1)
print(img)

[[[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 41  84  75]
  [ 41  84  75]
  [ 41  84  75]]

 [[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 41  84  75]
  [ 41  84  75]
  [ 41  84  75]]

 [[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 42  85  76]
  [ 42  85  76]
  [ 42  85  76]]

 ...

 [[122 145 171]
  [123 146 172]
  [124 145 172]
  ...
  [106 110 121]
  [106 110 121]
  [105 109 120]]

 [[119 142 168]
  [123 146 172]
  [126 147 174]
  ...
  [106 110 121]
  [105 109 120]
  [105 109 120]]

 [[117 140 166]
  [122 145 171]
  [126 147 174]
  ...
  [105 109 120]
  [105 109 120]
  [105 109 120]]]


In [7]:
# i can choose how many seconds i want the image appear then close it
cv2.imshow('image', img)
cv2.waitKey(5000)          # this mean open the img 5 seconds
cv2.destroyAllWindows()    # then close it