In [1]:
import cv2
import os
import numpy as np
import matplotlib.pyplot as plt
os.chdir('./data')

In [9]:
img = cv2.imread('house.jpg')
gray = cv2.cvtColor(img,cv2.COLOR_BGR2BGRA)

sift = cv2.SIFT_create()
kp = sift.detect(gray)
# res = cv2.drawKeypoints(gray,kp,img)
res = cv2.drawKeypoints(gray,kp,img,flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

cv2.imshow('res',res)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
sift = cv2.SIFT_create()
kp, des = sift.detectAndCompute(gray,None)
res = cv2.drawKeypoints(gray,kp,img)

print(des) # every column is a descriptor for a keypoint
cv2.imshow('res',res)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[  1.   3.   2. ...   0.   0.   1.]
 [  0.   0.   6. ...   0.   0.   0.]
 [  0.   1.  32. ...   0.   1.   0.]
 ...
 [ 14.  13.  79. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [158.   1.   0. ...   0.   0.   2.]]
