In [3]:
import cv2
import os
import numpy as np

In [ ]:
os.chdir('./data/')

In [18]:
def remove_distortion(cam_matrix,dist_coeff):
    img = cv2.imread('./distortion.jpg')
    img = cv2.resize(img,(1920,1080))

    height, width = img.shape[:2]

    # function helps optimize the camera matrix
    # this function returns a new camera matrix and a region of interest that will contain the undistorted part of the image
    new_cam_matrix, roi = cv2.getOptimalNewCameraMatrix(cam_matrix,dist_coeff,(width,height),1,(width,height)) # old_cam_matrix, dist_coeff, image_size, alpha, new_image_size
    print(new_cam_matrix)

    img_undistorted = cv2.undistort(img,cam_matrix,dist_coeff,None,new_cam_matrix) # img, old_cam_matrix, dist_coeff, new_cam_matrix
    # x,y,w,h = roi
    # img_undistorted = img_undistorted[y:y+h,x:x+w]

    cv2.line(img,(1769,103),(1780,922),(255,255,255),2)
    cv2.line(img_undistorted,(1769,103),(1780,922),(255,255,255),2)

    cv2.imshow('original',img)
    cv2.imshow('undistorted',img_undistorted)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [4]:
data = np.load('./calibration_data/MultiMatrix.npz')
cam_matrix = data['cam_matrix']
dist_matrix = data['dist_coeffs']
rvecs = data['rvecs']
tvecs = data['tvecs']

print(cam_matrix)
print(dist_matrix)
print(rvecs)
print(tvecs)

[[731.12850269   0.         410.04394907]
 [  0.         904.13035128 446.38632799]
 [  0.           0.           1.        ]]
[[-0.00981295 -0.74078757 -0.00354336 -0.01916192  0.60649542]]
[[[-0.09547118]
  [ 0.19873483]
  [ 1.46920487]]

 [[ 0.28075432]
  [ 1.20660571]
  [ 1.42607179]]

 [[-0.46151178]
  [ 1.2663048 ]
  [ 1.3980455 ]]

 [[ 0.2118138 ]
  [ 0.61805336]
  [ 1.35006007]]

 [[-0.08414572]
  [ 0.04420779]
  [ 0.90402126]]

 [[-0.2568581 ]
  [-0.61709611]
  [ 0.22028387]]

 [[-0.5896251 ]
  [ 0.1404878 ]
  [ 0.29767216]]

 [[ 0.39386409]
  [ 0.28481143]
  [-0.06939852]]

 [[-0.04042072]
  [ 0.3093176 ]
  [ 1.40182229]]

 [[-0.17542522]
  [ 0.51575994]
  [ 1.51628604]]]
[[[  64.66486459]
  [-102.6416511 ]
  [ 232.34412613]]

 [[ 223.96515359]
  [ -11.38079323]
  [ 312.19750661]]

 [[ 248.10753331]
  [  -9.53508693]
  [ 436.80479998]]

 [[ -44.63421643]
  [  -9.2439647 ]
  [ 568.06970546]]

 [[ -11.81756783]
  [ -82.67822216]
  [ 281.35362499]]

 [[-149.12262149]
  [ -55.326

In [19]:
remove_distortion(cam_matrix,dist_matrix)

[[988.52803887   0.         634.71959508]
 [  0.         737.28227873 448.10209376]
 [  0.           0.           1.        ]]


<h1>Why it does not work well</h1>


<h4>The undistortion process works best when applied to an image captured using the same camera for which the camera matrix (cam_matrix) and distortion coefficients (dist) were calculated, as these parameters are specific to that camera.</h4>