In [1]:
import cv2
import numpy as np
print(cv2.__version__)

4.6.0


<h1>working with images<h1>


In [15]:
# from google.colab import drive
# drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# show grayScale img
img = cv2.imread('cat_375.jpg', 0)
print(img)

[[ 56  56  56 ...  76  76  76]
 [ 56  56  56 ...  76  76  76]
 [ 56  56  56 ...  77  77  77]
 ...
 [150 151 151 ... 113 113 112]
 [147 151 153 ... 113 112 112]
 [145 150 153 ... 112 112 112]]


In [3]:
# not allowed on colab

cv2.imshow('image', img)
k = cv2.waitKey(0)

if k == 27:  # if i click on esc button "27 == esc"
    cv2.destroyAllWindows()

elif k == ord('s'):
    cv2.imwrite('cat_copy.png', img)
    cv2.destroyAllWindows()

QSocketNotifier: Can only be used with threads started with QThread


In [4]:
# i can choose how many seconds i want the image appear then close it
cv2.imshow('image', img)
cv2.waitKey(5000)          # this mean open the img 5 seconds
cv2.destroyAllWindows()    # then close it

In [6]:
# show colored img
img = cv2.imread('cat_375.jpg', 1)
print(img)

[[[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 41  84  75]
  [ 41  84  75]
  [ 41  84  75]]

 [[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 41  84  75]
  [ 41  84  75]
  [ 41  84  75]]

 [[ 29  60  59]
  [ 29  60  59]
  [ 28  60  59]
  ...
  [ 42  85  76]
  [ 42  85  76]
  [ 42  85  76]]

 ...

 [[122 145 171]
  [123 146 172]
  [124 145 172]
  ...
  [106 110 121]
  [106 110 121]
  [105 109 120]]

 [[119 142 168]
  [123 146 172]
  [126 147 174]
  ...
  [106 110 121]
  [105 109 120]
  [105 109 120]]

 [[117 140 166]
  [122 145 171]
  [126 147 174]
  ...
  [105 109 120]
  [105 109 120]
  [105 109 120]]]


In [7]:
# i can choose how many seconds i want the image appear then close it
cv2.imshow('image', img)
cv2.waitKey(5000)          # this mean open the img 5 seconds
cv2.destroyAllWindows()    # then close it

<h1>Working with videos</h1>


In [24]:
cap = cv2.VideoCapture(0)  # record video
# or
# cap = cv2.VideoCapture("path to your video")

# determining how frames are compressed and stored
fourcc = cv2.VideoWriter_fourcc(*"XVID")

out = cv2.VideoWriter('output.avi', fourcc, 20.0,
                      (640, 480))  # video name, fourcc, frames (how many photos i want to show per second), (width,height)

print(cap.isOpened())  # check if there is something wrong

while cap.isOpened():
    ret, frame = cap.read()  # return ret (bool) , frame if ret = False there is no frame
    if ret == True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        out.write(frame)  # save frame

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow('frame', gray)

        if cv2.waitKey(1) == ord('q'):
            break
    else:
        break

cap.release()  # close camera
out.release()  # close video
cv2.destroyAllWindows()

[ WARN:0@958.733] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1


True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0


<h3>Change Width&Height</h3>


In [25]:
cap = cv2.VideoCapture(0, cv2.CAP_V4L2)  # Use Video4Linux instead of GStreamer

fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))

print(cap.isOpened())

while cap.isOpened():
    ret, frame = cap.read()
    if ret == True:
        cap.set(3, 3000)  # width
        cap.set(4, 3000)  # height
        print(cap.get(3))
        print(cap.get(4))

        out.write(frame)
        color = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
        cv2.imshow('frame', color)
        if cv2.waitKey(1) == ord('q'):
            break

    else:
        break

cap.release()
out.release()
cv2.destroyAllWindows()

True
0.0
0.0


[ WARN:0@971.266] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
[ WARN:0@971.295] global ./modules/videoio/src/cap_gstreamer.cpp (2401) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src17 reported: Internal data stream error.
[ WARN:0@971.296] global ./modules/videoio/src/cap_gstreamer.cpp (897) startPipeline OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0@971.297] global ./modules/videoio/src/cap_gstreamer.cpp (1583) setProperty OpenCV | GStreamer warning: no pipeline
[ WARN:0@971.297] global ./modules/videoio/src/cap_gstreamer.cpp (1478) getProperty OpenCV | GStreamer warning: GStreamer: no pipeline
[ WARN:0@971.297] global ./modules/videoio/src/cap_gstreamer.cpp (1478) getProperty OpenCV | GStreamer warning: GStreamer: no pipeline
[ WARN:0@971.314] global ./modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GSt

<h1>put text on video</h1>


In [34]:
import datetime

cap = cv2.VideoCapture(0)  # Use Video4Linux instead of GStreamer

fourcc = cv2.VideoWriter_fourcc(*'XVID')
# out = cv2.VideoWriter('output.avi', fourcc, 20.0, (640, 480))

print(cap.isOpened())

while cap.isOpened():
    ret, frame = cap.read()
    if ret == True:
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        print(cap.get(3))
        print(cap.get(4))

        font = cv2.FONT_HERSHEY_SIMPLEX
        text = f"Width: {cap.get(3)} Height: {cap.get(4)}"
        date = str(datetime.datetime.now())

        # text, org, font, fontScale, color, thickness, lineType
        frame = cv2.putText(frame, date, (10, 50), font, 1,
                            (0, 255, 255), 2, cv2.LINE_AA)
        frame = cv2.putText(frame, text, (10, 100), font,
                            1, (0, 255, 255), 2, cv2.LINE_AA)
        # out.write(frame)

        color = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
        cv2.imshow('frame', frame)
        if cv2.waitKey(1) == ord('q'):
            break

    else:
        break

cap.release()
# out.release()
cv2.destroyAllWindows()

True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0


[ WARN:0@1806.708] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1


640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.

<h1>Handle Mouse Events</h1>


In [35]:
event = [i for i in dir(cv2) if "EVENT" in i]
event

['EVENT_FLAG_ALTKEY',
 'EVENT_FLAG_CTRLKEY',
 'EVENT_FLAG_LBUTTON',
 'EVENT_FLAG_MBUTTON',
 'EVENT_FLAG_RBUTTON',
 'EVENT_FLAG_SHIFTKEY',
 'EVENT_LBUTTONDBLCLK',
 'EVENT_LBUTTONDOWN',
 'EVENT_LBUTTONUP',
 'EVENT_MBUTTONDBLCLK',
 'EVENT_MBUTTONDOWN',
 'EVENT_MBUTTONUP',
 'EVENT_MOUSEHWHEEL',
 'EVENT_MOUSEMOVE',
 'EVENT_MOUSEWHEEL',
 'EVENT_RBUTTONDBLCLK',
 'EVENT_RBUTTONDOWN',
 'EVENT_RBUTTONUP']

In [60]:
def click_event(event, x, y, flags, params):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x, ',', y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ', ' + str(y)
        # img, text, position, font, size, color, thickness
        cv2.putText(img, strXY, (x, y), font, .5, (255, 255, 0), 2)
        cv2.imshow('image', img)

    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ', ' + str(green) + ', ' + str(red)
        cv2.putText(img, strBGR, (x, y), font, .5, (0, 255, 255), 2)
        cv2.imshow('image', img)


img = cv2.imread('cat_375.jpg', 1)
cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

25 , 23
153 , 129


<h1>Drawing a line between two points</h1>


In [43]:
def click_event(event, x, y, flags, params):
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img, (x, y), 13, (0, 0, 255), -1)
        points.append((x, y))
        if len(points) >= 2:
            cv2.line(img, points[-1], points[-2], (255, 0, 0), 5)

        cv2.imshow('image', img)


img = np.zeros((512, 512, 3), np.uint8)
cv2.imshow('image', img)
points = []
cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

<h1>open new window with the selected color</h1>


In [44]:
def click_event(event, x, y, flags, params):
    if event == cv2.EVENT_LBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]

        color_img = np.zeros((512, 512, 3), np.uint8)
        color_img[:] = [blue, green, red]

        cv2.imshow('color_image', color_img)


# img = np.zeros((512, 512, 3), np.uint8)
img = cv2.imread('cat_375.jpg', 1)
cv2.imshow('image', img)

cv2.setMouseCallback('image', click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()


<h1>image manipulation</h1>


In [6]:
img1 = cv2.imread('cat_375.jpg', 1)
img2 = cv2.imread('_.jpeg', 1)

<h3>separate rgb from img<h3>


In [7]:
B, G, R = cv2.split(img2)

print(B)
cv2.imshow('B', G)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[244 244 245 ...  39  39  40]
 [244 243 246 ...  39  39  40]
 [244 242 245 ...  40  40  41]
 ...
 [  3   3   3 ...   4   4   4]
 [  2   2   2 ...   5   5   5]
 [  2   2   2 ...   5   5   5]]


<h3>concatenate RGB<h3>


In [8]:
img2 = cv2.merge([B, G, R])

cv2.imshow('RGB', img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

<h3>copy head to new place<h3>


In [16]:
head = img2[22:198, 219:356]
img2[23:23+head.shape[0], 129:129+head.shape[1]] = head

cv2.imshow('img2', head)
cv2.waitKey(0)
cv2.destroyAllWindows()

<h3>merge 2 images<h3>


In [24]:
img1 = cv2.imread('cat_375.jpg', 1)
img2 = cv2.imread('_.jpeg', 1)

In [25]:
print(img1.shape)
img2.shape

(720, 1080, 3)


(690, 552, 3)

In [26]:
img1 = cv2.resize(img1, (512, 512))
img2 = cv2.resize(img2, (512, 512))
dst = cv2.add(img1, img2)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [27]:
# handle weight

# img1, weight1, img2, weight2, gamma "brightness"
dst = cv2.addWeighted(img1, 0.7, img2, 0.3, 0)
cv2.imshow('dst', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

<h1>Bitwise Operations<h1>
<h4>used in gray images<h4>


In [36]:
img1 = np.zeros((512, 512, 3), np.uint8)
img1 = cv2.rectangle(img1, (200, 0), (300, 100), (255, 255, 255), -1)

img2 = np.full((512, 512, 3), 255, np.uint8)  # white image
img2 = cv2.rectangle(img2, (0, 0), (250, 512), (0, 0, 0), -1)

cv2.imshow("img1", img1)
cv2.imshow("img2", img2)

# Bitwise AND
# bitwise_and = cv2.bitwise_and(img2, img1)
# cv2.imshow("bitwise_and", bitwise_and)

# Bitwise OR
# bitwise_or = cv2.bitwise_or(img2, img1)
# cv2.imshow("bitwise_or", bitwise_or)

# Bitwise XOR
# bitwise_xor = cv2.bitwise_xor(img2, img1)
# cv2.imshow("bitwise_xor", bitwise_xor)

# Bitwise NOT
# img2_bitwise_not = cv2.bitwise_not(img2)
# cv2.imshow("bitwise_not", img2_bitwise_not)
# img1_bitwise_not = cv2.bitwise_not(img1)
# cv2.imshow("bitwise_not", img1_bitwise_not)

cv2.waitKey(0)
cv2.destroyAllWindows()

<h1>control BGR<h1>


In [37]:
def nothing(x):
    print(x)


img = np.zeros((512, 512, 3), np.uint8)
cv2.namedWindow('image')

cv2.createTrackbar('B', 'image', 0, 255, nothing)
cv2.createTrackbar('G', 'image', 0, 255, nothing)
cv2.createTrackbar('R', 'image', 0, 255, nothing)

switch = "0 : OFF\n1 : ON"
cv2.createTrackbar(switch, 'image', 0, 1, nothing)
while True:
    cv2.imshow('image', img)
    # wait 1 millisecond and check if any key is pressed if yes break if no continue
    k = cv2.waitKey(1)
    if k == 27:
        break
    b = cv2.getTrackbarPos('B', 'image')
    g = cv2.getTrackbarPos('G', 'image')
    r = cv2.getTrackbarPos('R', 'image')
    s = cv2.getTrackbarPos(switch, 'image')
    if s == 0:
        img[:] = 0
    else:
        img[:] = [b, g, r]

cv2.destroyAllWindows()

5
6
12
16
21
24
26
28
30
31
32
33
34
35
36
37
38
39
40
41
43
44
46
48
49
51
52
54
56
58
59
60
61
63
1
3
5
9
12
15
17
20
22
24
27
28
29
30
31
32
34
36
37
38
39
40
41
42
44
46
47
48
50
51
52
54
58
61
63
65
67
69
73
76
79
83
87
92
95
100
102
105
108
112
114
116
118
122
124
126
129
131
134
137
140
143
145
149
151
154
157
159
162
164
166
169
171
172
174
176
178
180
182
184
186
188
190
192
194
196
199
203
205
208
210
213
216
218
219
221
223
225
226
227
229
230
233
235
236
238
240
243
244
245
246
247
248
67
71
75
80
83
87
89
91
94
96
98
99
101
104
106
108
111
114
118
120
124
126
128
129
131
134
135
137
139
141
143
144
145
146
147
148
150
152
155
158
159
161
162
163
165
166
167
168
169
170
172
174
178
180
183
186
188
191
192
194
196
199
201
205
208
211
215
217
220
223
225
227
228
229
230
231
233
235
236
237
238
240
242
243
244
245
246
247
248
249
250
251
252
254
255
254
255
250
254
255
254
252
249
247
246
245
244
242
240
237
236
233
231
229
227
226
223
221
220
219
218
217
216
215
214
213
212
2

<h1>Object Detection<h1>
<h4>Object Tracking Using HSV(Hue Saturation value) Color Space<h4>
<p>HSV is useful for tracking an object in a picture or video and will be useful more than RGB<p>


<h3>Photos detection<h3>


In [11]:
# Hue -> is the color
# Saturation -> is the intensity of the color
# Value -> is the brightness of the color

def nothing(x):
    print(x)


cv2.namedWindow('Tracking')
cv2.createTrackbar("LH", "Tracking", 0, 255, nothing)
cv2.createTrackbar("LS", "Tracking", 0, 255, nothing)
cv2.createTrackbar("LV", "Tracking", 0, 255, nothing)
cv2.createTrackbar("UH", "Tracking", 255, 255, nothing)
cv2.createTrackbar("US", "Tracking", 255, 255, nothing)
cv2.createTrackbar("UV", "Tracking", 255, 255, nothing)


while True:
    # change width and height of the pic
    frame = cv2.imread('cat_375.jpg', 1)
    frame = cv2.resize(frame, (512, 512))
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    lh = cv2.getTrackbarPos("LH", "Tracking")
    ls = cv2.getTrackbarPos("LS", "Tracking")
    lv = cv2.getTrackbarPos("LV", "Tracking")
    uh = cv2.getTrackbarPos("UH", "Tracking")
    us = cv2.getTrackbarPos("US", "Tracking")
    uv = cv2.getTrackbarPos("UV", "Tracking")

    l_b = np.array([lh, ls, lv])
    u_b = np.array([uh, us, uv])

    mask = cv2.inRange(hsv, l_b, u_b)

    res = cv2.bitwise_and(frame, frame, mask=mask)

    cv2.imshow("frame", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("res", res)

    key = cv2.waitKey(1)
    if key == 27:
        break

cv2.destroyAllWindows()

255
255
255


<h3>videos detection<h3>


In [13]:
def nothing(x):
    print(x)


cap = cv2.VideoCapture(0)
cv2.namedWindow('Tracking')
cv2.createTrackbar("LH", "Tracking", 0, 255, nothing)
cv2.createTrackbar("LS", "Tracking", 0, 255, nothing)
cv2.createTrackbar("LV", "Tracking", 0, 255, nothing)
cv2.createTrackbar("UH", "Tracking", 255, 255, nothing)
cv2.createTrackbar("US", "Tracking", 255, 255, nothing)
cv2.createTrackbar("UV", "Tracking", 255, 255, nothing)


while True:
    _, frame = cap.read()
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    lh = cv2.getTrackbarPos("LH", "Tracking")
    ls = cv2.getTrackbarPos("LS", "Tracking")
    lv = cv2.getTrackbarPos("LV", "Tracking")
    uh = cv2.getTrackbarPos("UH", "Tracking")
    us = cv2.getTrackbarPos("US", "Tracking")
    uv = cv2.getTrackbarPos("UV", "Tracking")

    l_b = np.array([lh, ls, lv])
    u_b = np.array([uh, us, uv])

    mask = cv2.inRange(hsv, l_b, u_b)

    res = cv2.bitwise_and(frame, frame, mask=mask)

    cv2.imshow("frame", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("res", res)

    key = cv2.waitKey(1)
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

[ WARN:0@3200.483] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1


255
255
255


qt.qpa.wayland: Wayland does not support QWindow::requestActivate()


1
2
4
5
8
9
11
12
13
14
16
19
20
22
24
25
27
30
31
32
33
34
35
36
37
38
40
41
42
43
44
45
46
48
51
52
54
56
57
59
60
62
63
65
66
68
69
71
74
75
77
78
79
80
82
84
85
87
88
89
90
91
92
95
96
98
100
101
103
104
102
99
96
93
90
89
87
85
84
80
79
77
76
74
71
70
68
67
66
65
64
65
67
1
2
4
5
7
8
9
10
11
12
14
15
17
21
23
25
28
31
32
34
35
36
40
41
46
47
49
51
52
54
57
58
57
56
53
51
50
48
47
43
41
39
36
34
31
28
26
25
23
21
20
17
15
14
12
10
9
7
4
3
1
0
4
10
13
17
19
21
23
24
26
27
29
33
35
38
40
43
46
48
49
51
52
54
58
60
61
63
65
66
69
71
74
76
77
80
81
82
84
86
87
88
90
92
94
96
99
101
102
105
106
110
111
113
116
117
119
120
124
125
128
130
131
133
134
135
137
138
141
142
143
144
145
147
148
150
154
156
157
159
161
162
165
167
168
170
172
173
174
177
179
182
184
185
187
191
193
195
196
195
194
192
190
189
186
184
183
181
180
178
175
174
172
170
169
167
165
163
161
160
158
157
156
154
153
151
149
148
147
145
144
143
142
143
252
244
241
237
232
227
226
224
223
220
218
217
215
214
212
209
208

<h1>Color Detection<h1>


In [6]:
cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

while True:
    ret, frame = cap.read()
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    height, width, _ = frame.shape
    cx = width//2
    cy = height//2

    HSV_center = hsv_frame[cx, cy]
    hsv_value = HSV_center[0]

    color = "black"
    if hsv_value < 5:
        color = "RED"
    elif hsv_value < 22:
        color = "ORANGE"
    elif hsv_value < 33:
        color = "YELLOW"
    elif hsv_value < 78:
        color = "GREEN"
    elif hsv_value < 131:
        color = "BLUE"
    elif hsv_value < 170:
        color = "VIOLET"

    BGR_center = frame[cx, cy]
    b, g, r = int(BGR_center[0]), int(BGR_center[1]), int(BGR_center[2])

    cv2.rectangle(frame, (cx-220, 15), (cx+200, 105), (255, 255, 255), -1)
    # color, text, position, font, font size, color, thickness
    cv2.putText(frame, color, (cx-220, 100), 0, 3, (b, g, r), 5)
    cv2.circle(frame, (cx, cy), 5, (25, 25, 25), 3)
    cv2.imshow("Frame", frame)

    key = cv2.waitKey(1)
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

[ WARN:0@599.363] global ./modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
