# vectors

In [1]:
import numpy as np

In [2]:
v1 = np.array([5,4,2])
v2 = np.array([1,3,2])

In [3]:
v1+v2, v1-v2

(array([6, 7, 4]), array([4, 1, 0]))

In [4]:
np.linalg.norm(v1) # get ||v1|| -> L2 norm

6.708203932499369

In [5]:
np.linalg.norm(v1,1) # get L1 norm

11.0

In [6]:
np.linalg.norm(v1,5) # get L5 norm

5.299757931808344

In [7]:
from math import inf
np.linalg.norm(v1, inf) # get L_max norm or L_inf norm

5.0

In [8]:
y = np.arange(0,20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
y_hat = np.arange(0,20) * 0.3
y_hat

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7])

In [10]:
e = y_hat - y
e

array([  0. ,  -0.7,  -1.4,  -2.1,  -2.8,  -3.5,  -4.2,  -4.9,  -5.6,
        -6.3,  -7. ,  -7.7,  -8.4,  -9.1,  -9.8, -10.5, -11.2, -11.9,
       -12.6, -13.3])

In [11]:
np.linalg.norm(e)

34.7893661914097

In [12]:
np.linalg.norm(e) ** 2/e.shape[0]

60.51500000000001

In [13]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_squared_error(y_true=y, y_pred=y_hat)

60.515

In [14]:
np.linalg.norm(e,1)/e.shape[0]

6.650000000000001

In [15]:
mean_absolute_error(y_pred=y_hat, y_true=y)

6.650000000000001

# Dot Product

In [16]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [17]:
# dot product
v1@v2

32

In [18]:
v1.shape

(3,)

In [19]:
v3 = np.array([[2,3,4]])
v3.shape

(1, 3)

In [20]:
v4 = np.array([[2],
            [3],
            [4]])
v4.shape

(3, 1)

In [21]:
v3@v4

array([[29]])

In [22]:
v4@v3

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])

#### REF & RREF

In [26]:
a = np.array([[1,-2],
            [3,-6]])

In [24]:
b = np.array([[1],
            [11]])

In [27]:
# Augmented matrix
Aug = np.concatenate((a,b), axis=1)
Aug

array([[ 1, -2,  1],
       [ 3, -6, 11]])

In [29]:
import sympy as sm
M = sm.Matrix(Aug)
M

Matrix([
[1, -2,  1],
[3, -6, 11]])

In [30]:
# will get the rref matrix and a tuple has the columns that has pivot
M.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [31]:
v = np.array([1,2])
u = np.array([5,7])

In [32]:
np.linalg.norm(v) * np.linalg.norm(u)

19.235384061671347

In [33]:
v@u

19

In [34]:
# this is bot row and column matrix
# its shape could be 1,4 when it multiply with a row vector
# its shape could be 4,1 when it multiply with a column vector
v = np.array([1,2,3,4])
v.shape

(4,)

In [35]:
m = np.array([[1,2,3,5]])
m.shape

(1, 4)

In [36]:
# 1,4 . 4,1 -> 1,1
m@v

array([34])

In [37]:
m = np.array([
    [1,2],
    [4,2],
    [7,2],
    [8,2],])

m.shape

(4, 2)

In [39]:
# 1,4 . 4,2 -> 1,2
v@m

array([62, 20])

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.linalg.inv(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.linspace(0,10,100) # start, end, num of points

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [45]:
# 0->1
np.random.rand(10)

array([0.78657645, 0.06422814, 0.20731048, 0.57978248, 0.14560067,
       0.54818768, 0.65708369, 0.95247344, 0.73583159, 0.35203634])

In [46]:
# mean=0 var=std=1
np.random.randn(10)

array([-0.18642167, -0.80826781, -0.4903117 , -1.62924296,  0.06564167,
        1.10644572,  0.55743778, -1.44536586,  0.79673636,  1.96248636])

In [47]:
np.random.randint(0,100,20) # start,end,size

array([33, 35, 99,  6, 32,  5, 25, 57, 87, 65, 19, 49, 60, 48, 66, 46, 83,
       60, 16, 19])

In [ ]:
v = np.array([1,2,3])
w = np.array([4,5,6])
v*w # scaler multiplication

# Gram-Schmidt Process & QR Decomposition

In [59]:
V = np.array([[1,2,3],
        [1,0,1],
        [1,1,-1]])

# qr sol
Q,R = np.linalg.qr(V)
Q@R

array([[ 9.993640e-01,  1.999062e+00,  2.998254e+00],
       [ 9.993640e-01, -3.340000e-04,  9.988580e-01],
       [ 9.993640e-01,  9.993640e-01, -9.990200e-01]])

In [60]:
# Gram-Schmidt Process
a = V[:, 0]
b = V[:, 1]
c = V[:, 2]

v1 = a
v2 = b - ((b@v1) / (v1@v1)) * v1
v3 = c - ((c@v1) / (v1@v1)) * v1 - ((c@v2) / (v2@v2)) * v2

q1 = v1 / np.linalg.norm(v1)
q2 = v2 / np.linalg.norm(v2)
q3 = v3 / np.linalg.norm(v3)

Q_manual = np.column_stack([q1, q2, q3])  # Stack q1, q2, q3 into a matrix
# sign_adjusted = np.allclose(abs(Q), abs(Q_manual))  # Compare absolute values
Q_manual

array([[ 0.57735027,  0.70710678,  0.40824829],
       [ 0.57735027, -0.70710678,  0.40824829],
       [ 0.57735027,  0.        , -0.81649658]])

# Eigenvalues and Eigenvectors

In [63]:
V = np.array([
    [1,2,3],
    [1, 0, 1],
    [1, 1, -1]])

eig_val, eig_vec = np.linalg.eig(V)
eig_val, eig_vec

(array([ 3., -1., -2.]),
 array([[-8.64241621e-01, -7.07106781e-01, -7.07106781e-01],
        [-3.92837101e-01,  7.07106781e-01,  6.47630098e-16],
        [-3.14269681e-01, -5.23364153e-17,  7.07106781e-01]]))

# Diagonalize

In [64]:
T = np.array([
    [1,1],
    [0,2]])

eig_val, eig_vec = np.linalg.eig(T)
eig_val, eig_vec

(array([1., 2.]),
 array([[1.        , 0.70710678],
        [0.        , 0.70710678]]))

In [68]:
C = eig_vec
C

array([[1.        , 0.70710678],
       [0.        , 0.70710678]])

In [66]:
D = np.diag(eig_val)
D

array([[1., 0.],
       [0., 2.]])

In [70]:
C_inv = np.linalg.inv(C)
C_inv

array([[ 1.        , -1.        ],
       [ 0.        ,  1.41421356]])

In [71]:
V = np.array(
    [[1],
    [-1]])

In [82]:
np.linalg.matrix_power(T, 5)@V

array([[-30],
       [-32]])

In [83]:
T_new = C@(D**5)@C_inv
T_new

array([[ 1., 31.],
       [ 0., 32.]])

In [84]:
T_new@V

array([[-30.],
       [-32.]])