In [2]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [3]:
# dot product
v1@v2

32

In [4]:
v1.shape

(3,)

In [5]:
v3 = np.array([[2,3,4]])
v3.shape

(1, 3)

In [7]:
v4 = np.array([[2],
            [3],
            [4]])
v4.shape

(3, 1)

In [9]:
v3@v4

array([[29]])

In [10]:
v4@v3

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])

# REF & RREF

In [12]:
b = np.array([[1],
            [11]])

In [13]:
a = np.array([[1,-2],
            [3,-6]])

In [15]:
# Augmented matrix
Aug = np.concatenate((a,b), axis=1)
Aug

array([[ 1, -2,  1],
       [ 3, -6, 11]])

In [16]:
import sympy as sm
M = sm.Matrix(Aug)

In [17]:
M

Matrix([
[1, -2,  1],
[3, -6, 11]])

In [19]:
# will get the rref matrix and a tuple has the columns that has pivot
M.rref()

(Matrix([
 [1, -2, 0],
 [0,  0, 1]]),
 (0, 2))

In [20]:
v = np.array([1,2])
u = np.array([5,7])

In [25]:
np.linalg.norm(v) * np.linalg.norm(u)

19.235384061671347

In [23]:
v@u

19

In [28]:
# this is bot row and column matrix
# its shape could be 1,4 when it multiply with a row vector
# its shape could be 4,1 when it multiply with a column vector
v = np.array([1,2,3,4])
v.shape

(4,)

In [45]:
m = np.array([[1,2,3,5]])
m.shape

(1, 4)

In [46]:
# 1,4 . 4,1 -> 1,1
m@v

array([34])

In [41]:
m = np.array([
    [1,2],
    [4,2],
    [7,2],
    [8,2],])

m.shape

(4, 2)

In [42]:
# 1,4 . 4,2 -> 1,2
v@m

array([62, 20])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.linalg.inv(np.eye(4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.linspace(0,10,100) # start, end, num of points

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [10]:
# 0->1
np.random.rand(10)

array([0.91049318, 0.54080449, 0.41593586, 0.26966163, 0.77655225,
       0.91638593, 0.20241252, 0.8415363 , 0.81690361, 0.8214139 ])

In [9]:
# mean=0 var=std=1
np.random.randn(10)

array([-0.12742109,  1.29318872,  1.09747189,  0.71780502, -0.54390651,
        0.38089171, -1.40822805,  1.59151214, -1.89291332, -1.05397972])

In [13]:
np.random.randint(0,100,20) # start,end,size

array([97, 18, 73, 83, 36, 94, 44, 15, 93, 72, 39, 98, 45,  8, 61, 29, 74,
       78,  5, 56])

In [14]:
v = np.array([1,2,3])
w = np.array([4,5,6])
v*w # scaler multiplication

array([ 4, 10, 18])