In [1]:
import numpy as np

In [2]:
v1 = np.array([5,4,2])
v2 = np.array([1,3,2])

In [4]:
v1+v2

array([6, 7, 4])

In [5]:
v1-v2

array([4, 1, 0])

In [6]:
np.linalg.norm(v1) # get ||v1|| -> L2 norm

6.708203932499369

In [7]:
np.linalg.norm(v1,1) # get L1 norm

11.0

In [8]:
np.linalg.norm(v1,5) # get L5 norm

5.299757931808344

In [10]:
from math import inf
np.linalg.norm(v1, inf) # get L_max norm or L_inf norm

5.0

In [14]:
y = np.arange(0,20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
y_hat = np.arange(0,20) * 0.3
y_hat

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7])

In [18]:
e = y_hat - y
e

array([  0. ,  -0.7,  -1.4,  -2.1,  -2.8,  -3.5,  -4.2,  -4.9,  -5.6,
        -6.3,  -7. ,  -7.7,  -8.4,  -9.1,  -9.8, -10.5, -11.2, -11.9,
       -12.6, -13.3])

In [19]:
np.linalg.norm(e)

34.7893661914097

In [20]:
np.linalg.norm(e) ** 2/e.shape[0]

60.51500000000001

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_squared_error(y_true=y, y_pred=y_hat)

60.515

In [22]:
np.linalg.norm(e,1)/e.shape[0]

6.650000000000001

In [23]:
mean_absolute_error(y_pred=y_hat, y_true=y)

6.650000000000001